query UndercoverRoom($id: ID!){
    undercoverRoom(where: { id: $id}){
        id
        host { id }
        name
        players {
            id
            user { id nickname }
            description
        }
    }
}